name: Make Documentation

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
    build:
      runs-on: ${{ matrix.os }}
        
      strategy:
        matrix:
          os: [ubuntu-22.04]

      steps:
        - name: Install popper
          run: |
            sudo apt-get install -y poppler-utils

        - name: Checkout Repo
          uses: actions/checkout@v3
            
        - name: Install
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Run installation.
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Make docs
          shell: bash
          run: |
            sphinx-build -b html docs build
            mkdir -p build/examples

        - name: Make example-for-sintef-1
          uses: xu-cheng/latex-action@v2
          with:
            working_directory: examples/db-2023
            latexmk_use_xelatex: true
            root_file: |
              db-chapter8.tex

        - name: Publish example
          run: |
            cp examples/db-2023/*.pdf build/examples
            python docs/pdf2imgs.py
        

        - name: Deploy Website
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
